kind: Pod
apiVersion: v1
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      workingDir: /home/jenkins
      image: gcr.io/kaniko-project/executor:debug
      envFrom:
        - secretRef:
            name: kaniko-secret
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
        - name: docker-cache
          mountPath: /kaniko/cache/
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
    - name: docker-cache
      persistentVolumeClaim:
        claimName: my-azurefile
