agent:
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      containers:
        - name: jnlp
          workingDir: /home/jenkins
        - name: kaniko
          workingDir: /home/jenkins
          image: gcr.io/kaniko-project/executor:debug
          envFrom:
            - secretRef:
                name: kaniko-secret
          command:
            - /busybox/cat
          tty: true
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: docker-config
        configMap:
          name: docker-config
